server:
  port: 80
spring:
  mvc:
    date-format: yyyy-MM-dd
    view:
      prefix: /
      suffix: .html
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/rbac?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
