server:
  port: 80
  servlet:
    context-path: /
spring:
  mvc:
    date-format: yyyy-MM-dd
    view:
      prefix: /
      suffix: .html
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/yoga?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL55Dialect
  main:
      allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true